#!/usr/bin/env bash

GCLOUD_BASE_CONF_STORE=~/.config/gcloud/
CRED_FILES=''
CRED_NAMES=''
#GOOGLE_APPLICATION_CREDENTIALS=''
BASH_PATH=$(which bash)

usage(){
  echo "$0: gcloud Application Default Credentials(ADCs) manipulator."
  echo ""
  exit 0
}

getent(){
  CRED_FILES=$(ls $GCLOUD_BASE_CONF_STORE/application_default_credentials.json_*)
  CRED_NAMES=$(echo $CRED_FILES | sed -e s:$GCLOUD_BASE_CONF_STORE/application_default_credentials\.json_::g)
} 
getent

errquit(){
  MSG=$1
  echo "$MSG"
  exit 1
}

getactive(){
  GENV="$(env | grep GOOGLE_APPLICATION_CREDENTIALS )"
  if [ -z "$GENV" ] ; then
    BASE_CRED_FILE=$GCLOUD_BASE_CONF_STORE/application_default_credentials.json
    if [ ! -f "$BASE_CRED_FILE" ] ; then
      errquit "ADC not set yet. please set that. quit."
    else
      cat $BASE_CRED_FILE
    fi
  else
    echo $GENV
  fi
}

if [ -z "$CRED_FILES" ] ; then
  errquit "file not found: $GCLOUD_BASE_CONF_STORE/application_default_credentials.json_*. quit."
fi

exist_check(){
  CHECK_FILE=$1
  if [ ! -f $CHECK_FILE ] ; then
    errquit "File not found. quit."
  fi
}

set_env_and_exec_bash(){
  REQ=$1
  CRED_JSON_PATH=$GCLOUD_BASE_CONF_STORE/application_default_credentials.json_${REQ}
  exist_check "$CRED_JSON_PATH"
  export GOOGLE_APPLICATION_CREDENTIALS=$CRED_JSON_PATH
  exec "$BASH_PATH"
}

if [ $# -eq 0 ] ; then
  getactive
else
  case $1 in
  s)
    REQ=$2
    set_env_and_exec_bash $REQ
  ;;
  l)
    echo $CRED_NAMES
  ;;
  h)
    usage
  ;;
  *)
    :
  ;;
  esac
fi

